# Generated by Django 3.1.7 on 2021-05-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No attribute', max_length=32)),
                ('key', models.CharField(default='no-attribute', max_length=32)),
                ('tags', models.ManyToManyField(to='online_shop.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_shop.tag'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Missing value', max_length=260)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(to='online_shop.AttributeValue'),
        ),
        migrations.AddField(
            model_name='tag',
            name='attributes',
            field=models.ManyToManyField(to='online_shop.Attribute'),
        ),
    ]
